# docker run --name lumiere-api-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e
# POSTGRESQL_DATABASE=lumiereapi -p 5432:5432 bitnami/postgresql

version: '3'
services:
  lumiere-api-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=lumiereapi
